baseurl: '/garden/'
permalink: pretty
title: "Sandy's Gardening & Landscape Design"
remote_theme: "zerostaticthemes/jekyll-serif-theme"

logo:
  mobile: "images/logo/logo-mobile.svg"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/logo/sandy-logo.svg"
  desktop_height: "32px"
  desktop_width: "35px"

home: 
  limit_services: 6

collections:
  designs:
    output: true
    sort_by: weight
  gardening:
    output: true
    sort_by: weight
  team:
    output: true

defaults:
  - scope:
      path: ""
#      type: "services"
      type: "gardening"
    values:
      layout: "garden"
#      layout: "service"
  - scope:
      path: ""
      type: "designs"
    values:
      layout: "design"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
